when not declared ATCODER_EXTRA_MATH_XOR_BASIS_HPP:
  const ATCODER_EXTRA_MATH_XOR_BASIS_HPP* = 1

  type
    XorBasis*[T: SomeInteger] = object
      maxLog*: int
      basis*: seq[T]
      rankValue: int

  proc initXorBasis*[T: SomeInteger](maxLog: int = 60): XorBasis[T] =
    ## Creates an empty XOR basis.
    ##
    ## `maxLog` is the highest bit index to inspect.
    doAssert 0 <= maxLog and maxLog < 64
    result.maxLog = maxLog
    result.basis = newSeq[T](maxLog + 1)
    result.rankValue = 0

  proc bitAt[T: SomeInteger](x: T, b: int): bool {.inline.} =
    ((uint64(x) shr b) and 1'u64) != 0'u64

  proc xorAsT[T: SomeInteger](a, b: T): T {.inline.} =
    T(uint64(a) xor uint64(b))

  proc rank*[T: SomeInteger](xb: XorBasis[T]): int {.inline.} =
    ## Returns the number of independent basis vectors.
    xb.rankValue

  proc len*[T: SomeInteger](xb: XorBasis[T]): int {.inline.} =
    ## Alias of `rank`.
    xb.rankValue

  proc empty*[T: SomeInteger](xb: XorBasis[T]): bool {.inline.} =
    xb.rankValue == 0

  proc add*[T: SomeInteger](xb: var XorBasis[T], x: T): bool =
    ## Adds `x` to the basis.
    ##
    ## Returns `true` if `x` was linearly independent from the existing basis.
    var y = x

    for b in countdown(xb.maxLog, 0):
      if not bitAt(y, b):
        continue

      if xb.basis[b] == T(0):
        xb.basis[b] = y
        xb.rankValue.inc
        return true

      y = xorAsT(y, xb.basis[b])

    false

  proc addAll*[T: SomeInteger](xb: var XorBasis[T], xs: openArray[T]) =
    ## Adds all values in `xs`.
    for x in xs:
      discard xb.add(x)

  proc reduce*[T: SomeInteger](xb: XorBasis[T], x: T): T =
    ## Reduces `x` by the current basis and returns the remaining value.
    ##
    ## The result is zero iff `x` is representable as an XOR of basis vectors.
    result = x

    for b in countdown(xb.maxLog, 0):
      if bitAt(result, b) and xb.basis[b] != T(0):
        result = xorAsT(result, xb.basis[b])

  proc canRepresent*[T: SomeInteger](xb: XorBasis[T], x: T): bool =
    ## Returns whether `x` is representable by XORing inserted values.
    xb.reduce(x) == T(0)

  proc contains*[T: SomeInteger](xb: XorBasis[T], x: T): bool =
    ## Enables `x in xb` as a representation test.
    xb.canRepresent(x)

  proc maxXor*[T: SomeInteger](xb: XorBasis[T], x: T): T =
    ## Returns the maximum value of `x xor y`,
    ## where `y` ranges over all representable XOR values.
    result = x

    for b in countdown(xb.maxLog, 0):
      if xb.basis[b] == T(0):
        continue

      let cand = xorAsT(result, xb.basis[b])

      if uint64(cand) > uint64(result):
        result = cand

  proc maxXor*[T: SomeInteger](xb: XorBasis[T]): T =
    ## Returns the maximum representable XOR value.
    xb.maxXor(T(0))

  proc minXor*[T: SomeInteger](xb: XorBasis[T], x: T): T =
    ## Returns the minimum value of `x xor y`,
    ## where `y` ranges over all representable XOR values.
    xb.reduce(x)

  proc basisSeq*[T: SomeInteger](xb: XorBasis[T]): seq[T] =
    ## Returns non-zero basis vectors from high bit to low bit.
    for b in countdown(xb.maxLog, 0):
      if xb.basis[b] != T(0):
        result.add xb.basis[b]

  proc merge*[T: SomeInteger](a, b: XorBasis[T]): XorBasis[T] =
    ## Returns a basis generated by all values from `a` and `b`.
    result = initXorBasis[T](max(a.maxLog, b.maxLog))

    for x in a.basis:
      if x != T(0):
        discard result.add(x)

    for x in b.basis:
      if x != T(0):
        discard result.add(x)
