name: oj-verify

on:
  workflow_dispatch:
    inputs:
      nim-version:
        description: 'Nim version used for oj-verify'
        required: true
        default: '2.2.4'
      verify-target:
        description: 'oj-verify target'
        required: true
        default: 'all'

jobs:
  oj-verify:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v4

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ inputs.nim-version }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install verification-helper
        run: |
          python -m pip install -U pip
          python -m pip install -U online-judge-verify-helper

      - name: Run oj-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd src
          oj-verify ${{ inputs.verify-target }}
